name: Broken Solve
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "23.11.0-1"
          auto-activate-base: true
          activate-environment: ""
          python-version: "3.8"
      - shell: bash
        run: conda info
      - shell: bash
        run: conda config --show-sources
      - shell: bash
        run: conda list --show-channel-urls
      - shell: bash
        run: conda install libsolv=0.7.22 libmambapy=1.5.2 -c conda-forge --yes
      - shell: bash
        run: conda env create --name ok --file ok.yml --dry-run
      - shell: bash
        run: conda env create --name broken --file broken.yml --dry-run -vvv