name: Broken Solve
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          installer-url: "https://repo.anaconda.com/miniconda/Miniconda3-py38_23.10.0-1-Linux-x86_64.sh"
          auto-activate-base: true
          activate-environment: "true"
      - shell: bash
        run: conda info
      - shell: bash
        run: conda config --show-sources
      - shell: bash
        run: conda list --show-channel-urls
      - shell: bash
        run: conda install libsolv=0.7.22 -c conda-forge --yes
      - shell: bash
        run: conda env create --name ok --file ok.yml --dry-run
      - shell: bash
        run: conda env create --name broken --file broken.yml --dry-run -vvv